services:
  ngrok:
    image: ngrok/ngrok:latest
    networks:
      - ngrok_network
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
  
  bot:
    build: .
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql_db
    ports:
      - '8001:8001'
    # depends_on:
    #   - ngrok
    command: sh -c 'python main.py'
    networks:
      - bot_network
      - ngrok_network
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

  psql_db:
    image: postgres:14
    # restart: always
    networks:
      - bot_network
    # ports:
    #   - '5432:5432'
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Moscow
    cpus: '1.0'
    mem_limit: 2g
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # command: postgres -c max_connections=200 -c shared_buffers=2GB
    # command: postgres -c max_connections=100 -c shared_buffers=2GB -c work_mem=16MB -c maintenance_work_mem=512MB -c effective_cache_size=6GB
    logging:
      driver: "json-file"

  # redis_tg_bot_db:
  #   image: redis:alpine
  #   restart: on-failure
  #   networks:
  #     - redis_network
  #   # ports:
  #   #   - 6379:6379
  #   env_file:
  #     - ./.env
  #   command: redis-server --requirepass ${REDIS_PASSWORD} --save "10" "1" --appendonly no
  #   # sh -c "echo 1 > /proc/sys/vm/overcommit_memory && redis-server --save 900 1 --loglevel warning"
  #   volumes:
  #     - redis_tg_bot_data:/data
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-size: "20m"

networks:
  bot_network:
    name: local_network
    external: true
  ngrok_network:

volumes:
  postgres-data: