from pydantic import BaseModel, Field


class UTMSchema(BaseModel):
    keitaro_id: str | None = Field(default=None)
    utm_source: str | None = Field(default=None)
    utm_medium: str | None = Field(default=None)
    utm_campaign: str | None = Field(default=None)
    utm_content: str | None = Field(default=None)
    utm_term: str | None = Field(default=None)
    banner_id: str | None = Field(default=None)
    campaign_name: str | None = Field(default=None)
    campaign_name_lat: str | None = Field(default=None)
    campaign_type: str | None = Field(default=None)
    campaign_id: str | None = Field(default=None)
    creative_id: str | None = Field(default=None)
    device_type: str | None = Field(default=None)
    gbid: str | None = Field(default=None)
    keyword: str | None = Field(default=None)
    phrase_id: str | None = Field(default=None)
    coef_goal_context_id: str | None = Field(default=None)
    match_type: str | None = Field(default=None)
    matched_keyword: str | None = Field(default=None)
    adtarget_name: str | None = Field(default=None)
    adtarget_id: str | None = Field(default=None)
    position: str | None = Field(default=None)
    position_type: str | None = Field(default=None)
    source: str | None = Field(default=None)
    source_type: str | None = Field(default=None)
    region_name: str | None = Field(default=None)
    region_id: str | None = Field(default=None)
    yclid: str | None = Field(default=None)
    client_id: str | None = Field(default=None)
