"""add UserProductJob model

Revision ID: 2eec97839e0e
Revises: a1802ecdf7f0
Create Date: 2025-03-11 12:52:06.367591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eec97839e0e'
down_revision: Union[str, None] = 'a1802ecdf7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('user_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_product_id'], ['user_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_product_job_id'), 'user_product_job', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_job_id'), table_name='user_product_job')
    op.drop_table('user_product_job')
    # ### end Alembic commands ###
