"""Edit structure DB, add Ozon_punkt DB model

Revision ID: 3e5bca171c97
Revises: 18fc7e23782f
Create Date: 2025-02-26 15:33:22.531744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5bca171c97'
down_revision: Union[str, None] = '18fc7e23782f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_punkts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ozon_punkts_id'), 'ozon_punkts', ['id'], unique=False)
    op.add_column('ozon_products', sa.Column('ozon_punkt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ozon_products', 'ozon_punkts', ['ozon_punkt_id'], ['id'])
    op.add_column('wb_punkts', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('wb_punkts', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wb_punkts', 'city')
    op.drop_column('wb_punkts', 'index')
    op.drop_constraint(None, 'ozon_products', type_='foreignkey')
    op.drop_column('ozon_products', 'ozon_punkt_id')
    op.drop_index(op.f('ix_ozon_punkts_id'), table_name='ozon_punkts')
    op.drop_table('ozon_punkts')
    # ### end Alembic commands ###
