"""Add total product count fields to Users model

Revision ID: 522f84193bac
Revises: 38640b2649ff
Create Date: 2025-05-13 13:12:36.254547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522f84193bac'
down_revision: Union[str, None] = '38640b2649ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wb_total_count', sa.Integer(), server_default='0'))
    op.add_column('users', sa.Column('ozon_total_count', sa.Integer(), server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ozon_total_count')
    op.drop_column('users', 'wb_total_count')
    # ### end Alembic commands ###
