"""Edit *_punkt_id for WB and Ozon product to nullable=True

Revision ID: 67f00888d2d2
Revises: 3e5bca171c97
Create Date: 2025-02-26 15:52:51.022274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f00888d2d2'
down_revision: Union[str, None] = '3e5bca171c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ozon_products', 'ozon_punkt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wb_products', 'wb_punkt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wb_products', 'wb_punkt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ozon_products', 'ozon_punkt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
