"""add UTM DB model

Revision ID: a103835aa60a
Revises: 2eec97839e0e
Create Date: 2025-03-18 12:17:34.331757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a103835aa60a'
down_revision: Union[str, None] = '2eec97839e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keitaro_id', sa.String(), nullable=True),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('utm_content', sa.String(), nullable=True),
    sa.Column('utm_term', sa.String(), nullable=True),
    sa.Column('banner_id', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('campaign_name_lat', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('creative_id', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('gbid', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('phrase_id', sa.String(), nullable=True),
    sa.Column('coef_goal_context_id', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('matched_keyword', sa.String(), nullable=True),
    sa.Column('adtarget_name', sa.String(), nullable=True),
    sa.Column('adtarget_id', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('position_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('yclid', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utms_id'), 'utms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utms_id'), table_name='utms')
    op.drop_table('utms')
    # ### end Alembic commands ###
