"""add basic price for Product models

Revision ID: b28236ef24f0
Revises: a21d15898294
Create Date: 2025-01-29 17:23:41.033737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28236ef24f0'
down_revision: Union[str, None] = 'a21d15898294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ozon_products', sa.Column('basic_price', sa.Float(), nullable=True))
    op.add_column('wb_products', sa.Column('basic_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wb_products', 'basic_price')
    op.drop_column('ozon_products', 'basic_price')
    # ### end Alembic commands ###
