"""remove basic price from WbProduct model

Revision ID: b5453149b690
Revises: a21d15898294
Create Date: 2025-01-29 21:04:59.415134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5453149b690'
down_revision: Union[str, None] = 'a21d15898294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ozon_products', sa.Column('basic_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ozon_products', 'basic_price')
    # ### end Alembic commands ###
