"""Add ProductCityGraphic model

Revision ID: c74f9b211e82
Revises: 4302d4961590
Create Date: 2025-04-02 15:57:53.936384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74f9b211e82'
down_revision: Union[str, None] = '4302d4961590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_city_graphics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('photo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_city_graphics_id'), 'product_city_graphics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_city_graphics_id'), table_name='product_city_graphics')
    op.drop_table('product_city_graphics')
    # ### end Alembic commands ###
