"""Add Category and ChannelLink DB model

Revision ID: cc5bf10fe49b
Revises: 522f84193bac
Create Date: 2025-05-20 14:00:52.378035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5bf10fe49b'
down_revision: Union[str, None] = '522f84193bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('channel_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_links_id'), 'channel_links', ['id'], unique=False)
    op.create_table('category_channel_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('channel_link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['channel_link_id'], ['channel_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_channel_association_category_id'), 'category_channel_association', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_channel_association_channel_link_id'), 'category_channel_association', ['channel_link_id'], unique=False)
    op.create_table('popular_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('start_price', sa.Integer(), nullable=True),
    sa.Column('actual_price', sa.Integer(), nullable=True),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popular_products_id'), 'popular_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_products_id'), table_name='popular_products')
    op.drop_table('popular_products')
    op.drop_index(op.f('ix_category_channel_association_channel_link_id'), table_name='category_channel_association')
    op.drop_index(op.f('ix_category_channel_association_category_id'), table_name='category_channel_association')
    op.drop_table('category_channel_association')
    op.drop_index(op.f('ix_channel_links_id'), table_name='channel_links')
    op.drop_table('channel_links')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
